name: KittenAnnoPaper
main: com.iluyf.mc.Anno
version: 3.0
api-version: 1.19
author: Kittengarten
commands:
  kittenanno:
    description: Get today's date. (WorldTreeAnno)
    aliases: [anno]
permissions:
  kittenanno.*:
    description: Gives access to all kittenanno commands.
    children:
      kittenanno.anno: true
  kittenanno.anno:
    description: Allows you to use WorldTreeAnno.
    default: true